apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zammad-websocket
  namespace: zammad
  labels:
    component: websocket
    app: zammad
spec:
  serviceName: zammad-websocket
  replicas: 1
  template:
    metadata:
      labels:
        component: websocket
        app: zammad
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zammad-websocket
        image: monotek/zammad-docker-compose:zammad
        args: [ "zammad-websocket" ]
        ports:
        - containerPort: 6042
          name: websocket
        imagePullPolicy: Always
        securityContext:
          privileged: true
