---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zammad
  namespace: zammad
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zammad-elasticsearch
  namespace: zammad
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
      
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zammad-postgresql
  namespace: zammad
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
