apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zammad-scheduler
  namespace: zammad
  labels:
    component: scheduler
    app: zammad
spec:
  serviceName: zammad-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        app: zammad
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      containers:
      - name: zammad-scheduler
        image: monotek/zammad-docker-compose:zammad
        args: [ "zammad-scheduler" ]
        imagePullPolicy: Always
        securityContext:
          privileged: true
