apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zammad-nfs
  namespace: zammad
  labels:
    component: netfs
    app: zammad
spec:
  serviceName: zammad-nfs
  replicas: 1
  template:
    metadata:
      labels:
        component: netfs
        app: nfs
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      - name: zammad-storage
        persistentVolumeClaim:
          claimName: zammad-storage
      containers:
      - name: zammad-nfs
        image: gcr.io/google_containers/volume-nfs
        imagePullPolicy: Always
        ports:
        - containerPort: 2049
          name: nfsserver
        - containerPort: 111
          name: rpc
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /exports
          name: zammad-storage
